# Common configuration values shared across all environments
replicaCount: 2

image:
  repository: barath1406/user-portal
  tag: "2.5.11"
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  name: "barath-user-portal-sa"
  iamRole: "arn:aws:iam::891377149147:role/barath-user-portal-role"

podAnnotations: {}

ingress:
  enabled: true
  ingressClassName: "nginx"
  serviceName: "barath-user-portal-service"
  servicePort: 80
  host: "k8s-ingressn-ingressn-4acd914e54-6ed70e4f45dfc4c1.elb.us-west-2.amazonaws.com" 
  path: "/"
  pathType: "ImplementationSpecific"
  namespace: "workload"
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1 
    
service:
  type: ClusterIP
  port: 80
  targetPort: 5000
  protocol: TCP
  name: http

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

livenessProbe:
  httpGet:
    path: /
    port: 5000
  initialDelaySeconds: 30
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /
    port: 5000
  initialDelaySeconds: 5
  periodSeconds: 5
  
aws:
  region: "us-west-2"
  secretKey: "barath-aurora-cluster-master-password"

flaskSecretKey: b"\xfd{H\xe5<\x95\xf9\xe3\x96.5\xd1\x01O<!\xd5\xa2\xa0\x9fR"\xa1\xa8"
